# coding=utf-8
import openai


def common_sense(request: str) -> str:
    """
    Generates a human-like response to a short request by leveraging a pre-trained language model. This function can be used for a wide range of natural language understanding
    tasks, such as answering questions, generating text, and more.

    Example:
        >>> common_sense("What is the capital of France?")

    Args:
        request (str): A string representing the user's request that is 500 characters long or less.

    Returns:
        str: The response generated by the AI model for the given request. This response can vary greatly
        depending on the nature of the request, from simple factual answers to more complex textual content.
    """

    if len(request) > 500:
        raise ValueError("The request must be less than 500 characters long.")

    messages = [
        {"role": "user", "content": request}
    ]

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )

    first_choice = response.choices[0]
    message = first_choice["message"]
    return message["content"]
