# coding=utf-8
import openai


def common_sense(request: str) -> str:
    """Generates contextually appropriate responses to user queries by leveraging a pre-trained AI language model, suitable for various natural language understanding
    tasks.

    This function employs a sophisticated language model to interpret and respond to user requests, useful in a wide variety of natural language understanding tasks. These tasks may include but are not limited to answering questions, generating text, summarizing content, and more.

    Example:
        >>> common_sense("What is the capital of France?")

    Args:
        request (str): The user's request as a string, which should be 500 characters or fewer.

    Returns:
        str: A human-like response generated by the AI model based on the given request. The nature and complexity of this response can vary significantly, ranging from simple factual answers to more nuanced, detailed textual content.
    """

    if len(request) > 500:
        raise ValueError("The request must be less than 500 characters long.")

    messages = [
        {"role": "user", "content": request}
    ]

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )

    first_choice = response.choices[0]
    message = first_choice["message"]
    return message["content"]
